# Generated by Django 5.0.6 on 2024-05-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchdogbark',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchdogbark',
            name='title',
            field=models.CharField(default='price is what you want', max_length=200),
            preserve_default=False,
        ),
    ]
