# Generated by Django 5.0.6 on 2024-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_watchdogbark_price_watchdogbark_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchdogbark',
            name='action_taken',
            field=models.BooleanField(default=False),
        ),
    ]
